# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWin(object):
    def setupUi(self, MainWin):
        MainWin.setObjectName("MainWin")
        MainWin.resize(473, 420)
        self.gridLayout = QtWidgets.QGridLayout(MainWin)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(MainWin)
        self.tabWidget.setStyleSheet("QTabBar::tab {\n"
"min-width: 30ex;\n"
"min-height: 10ex;\n"
"color:#464646;\n"
"font:20px \"Microsoft YaHei\";\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_5.addWidget(self.lineEdit_3)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_5.addWidget(self.pushButton_7)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_6.addWidget(self.lineEdit_4)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_6.addWidget(self.pushButton_8)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_10.addWidget(self.lineEdit_8)
        self.pushButton_13 = QtWidgets.QPushButton(self.tab)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_10.addWidget(self.pushButton_13)
        self.gridLayout_4.addLayout(self.horizontalLayout_10, 3, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 3, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_4.addWidget(self.pushButton_5)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 2)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 0, 3, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 1, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 2, 2, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.m_res = QtWidgets.QLineEdit(self.groupBox_7)
        self.m_res.setObjectName("m_res")
        self.gridLayout_7.addWidget(self.m_res, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_7, 4, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(6, -1, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.trisk_w = QtWidgets.QLineEdit(self.tab_2)
        self.trisk_w.setObjectName("trisk_w")
        self.gridLayout_3.addWidget(self.trisk_w, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 2, 1, 1)
        self.button_rams = QtWidgets.QPushButton(self.tab_2)
        self.button_rams.setObjectName("button_rams")
        self.gridLayout_3.addWidget(self.button_rams, 0, 6, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 5, 1, 1)
        self.trisk_line = QtWidgets.QLineEdit(self.tab_2)
        self.trisk_line.setObjectName("trisk_line")
        self.gridLayout_3.addWidget(self.trisk_line, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_3.addWidget(self.lineEdit_9, 2, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 0, 3, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_3.addWidget(self.lineEdit_10, 0, 4, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 1, 3, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 2, 4, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_3.addWidget(self.lineEdit_11, 1, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 3, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_3, 0, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem3, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.r_res = QtWidgets.QLineEdit(self.groupBox_2)
        self.r_res.setObjectName("r_res")
        self.gridLayout_6.addWidget(self.r_res, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_2, 3, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.a_res = QtWidgets.QLineEdit(self.groupBox_3)
        self.a_res.setObjectName("a_res")
        self.gridLayout_8.addWidget(self.a_res, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_3, 2, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 1)
        self.trisk_rank = QtWidgets.QTableWidget(self.groupBox)
        self.trisk_rank.setShowGrid(True)
        self.trisk_rank.setGridStyle(QtCore.Qt.DashLine)
        self.trisk_rank.setRowCount(4)
        self.trisk_rank.setColumnCount(2)
        self.trisk_rank.setObjectName("trisk_rank")
        self.gridLayout_5.addWidget(self.trisk_rank, 3, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 1, 0, 1, 1)
        self.allrisk = QtWidgets.QLineEdit(self.groupBox)
        self.allrisk.setObjectName("allrisk")
        self.gridLayout_5.addWidget(self.allrisk, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 3, 0, 1, 1)
        self.singrisk = QtWidgets.QLineEdit(self.groupBox)
        self.singrisk.setReadOnly(True)
        self.singrisk.setObjectName("singrisk")
        self.gridLayout_5.addWidget(self.singrisk, 0, 1, 1, 1)
        self.trisk = QtWidgets.QLineEdit(self.groupBox)
        self.trisk.setObjectName("trisk")
        self.gridLayout_5.addWidget(self.trisk, 1, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.button_analyse = QtWidgets.QPushButton(self.groupBox)
        self.button_analyse.setObjectName("button_analyse")
        self.horizontalLayout_7.addWidget(self.button_analyse)
        self.pushButton_table = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_table.setObjectName("pushButton_table")
        self.horizontalLayout_7.addWidget(self.pushButton_table)
        self.gridLayout_5.addLayout(self.horizontalLayout_7, 4, 1, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox, 2, 0, 3, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_improve_pic = QtWidgets.QLabel(self.tab_3)
        self.label_improve_pic.setMinimumSize(QtCore.QSize(300, 150))
        self.label_improve_pic.setText("")
        self.label_improve_pic.setObjectName("label_improve_pic")
        self.gridLayout_19.addWidget(self.label_improve_pic, 1, 0, 1, 1)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_35 = QtWidgets.QLabel(self.tab_3)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_14.addWidget(self.label_35)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.horizontalLayout_14.addWidget(self.lineEdit_20)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.gridLayout_18.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_13.addWidget(self.label_16)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_13.addWidget(self.lineEdit_7)
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_13.addWidget(self.label_17)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_19.setText("")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.horizontalLayout_13.addWidget(self.lineEdit_19)
        self.label_34 = QtWidgets.QLabel(self.tab_3)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_13.addWidget(self.label_34)
        self.gridLayout_18.addLayout(self.horizontalLayout_13, 0, 0, 1, 3)
        self.button_improve = QtWidgets.QPushButton(self.tab_3)
        self.button_improve.setObjectName("button_improve")
        self.gridLayout_18.addWidget(self.button_improve, 1, 1, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_18.addWidget(self.pushButton_16, 1, 2, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_18, 0, 0, 1, 3)
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.label = QtWidgets.QLabel(MainWin)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(MainWin)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWin)

    def retranslateUi(self, MainWin):
        _translate = QtCore.QCoreApplication.translate
        MainWin.setWindowTitle(_translate("MainWin", "支撑工具"))
        self.label_4.setText(_translate("MainWin", "车站数据"))
        self.pushButton_7.setText(_translate("MainWin", "选择"))
        self.label_2.setText(_translate("MainWin", "客流数据"))
        self.pushButton.setText(_translate("MainWin", "选择"))
        self.label_5.setText(_translate("MainWin", "区间数据"))
        self.pushButton_8.setText(_translate("MainWin", "选择"))
        self.label_9.setText(_translate("MainWin", "单点风险"))
        self.pushButton_13.setText(_translate("MainWin", "选择"))
        self.pushButton_2.setText(_translate("MainWin", "确认"))
        self.label_3.setText(_translate("MainWin", "线路数据"))
        self.pushButton_5.setText(_translate("MainWin", "选择"))
        self.label_6.setText(_translate("MainWin", "风险概率函数"))
        self.lineEdit_5.setText(_translate("MainWin", "1/(1+e^(-6x + 7)"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWin", "单位：小时"))
        self.label_7.setText(_translate("MainWin", "最小单位时间"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWin", "基础数据"))
        self.groupBox_7.setTitle(_translate("MainWin", "可维修性评估"))
        self.label_12.setText(_translate("MainWin", "运能风险分级"))
        self.button_rams.setText(_translate("MainWin", "开始评估"))
        self.label_18.setText(_translate("MainWin", "可用性阈值"))
        self.label_11.setText(_translate("MainWin", "运能风险权重"))
        self.label_19.setText(_translate("MainWin", "可靠性阈值"))
        self.label_20.setText(_translate("MainWin", "可维修性阈值"))
        self.comboBox.setCurrentText(_translate("MainWin", "最短路径"))
        self.comboBox.setItemText(0, _translate("MainWin", "最短路径"))
        self.comboBox.setItemText(1, _translate("MainWin", "均匀分配"))
        self.label_10.setText(_translate("MainWin", "客流分配策略"))
        self.groupBox_2.setTitle(_translate("MainWin", "可靠性评估"))
        self.groupBox_3.setTitle(_translate("MainWin", "可用性评估"))
        self.groupBox.setTitle(_translate("MainWin", "安全性评估"))
        self.label_14.setText(_translate("MainWin", "全局安全风险"))
        self.label_8.setText(_translate("MainWin", "单点风险(元)"))
        self.label_13.setText(_translate("MainWin", "运能风险"))
        self.label_15.setText(_translate("MainWin", "运能风险分级"))
        self.button_analyse.setText(_translate("MainWin", "图表分析"))
        self.pushButton_table.setText(_translate("MainWin", "数据查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWin", "RAMS评估"))
        self.label_35.setText(_translate("MainWin", "允许分配的\n"
"路径长度与最\n"
"短路径的比值"))
        self.label_16.setText(_translate("MainWin", "选择增强时间"))
        self.label_17.setText(_translate("MainWin", "天"))
        self.label_34.setText(_translate("MainWin", "时间单位"))
        self.button_improve.setText(_translate("MainWin", "开始增强"))
        self.pushButton_16.setText(_translate("MainWin", "下载详细结果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWin", "安全增强"))
        self.label.setText(_translate("MainWin", "区域轨道交通RAMS评估支撑工具"))

